export const jwtConstants = {
  secret:
    'BABY SHARK DO DOD DOD DO, DADDY SHARK DO DOD DOD DO, MOMMY SHARK DO DOD DOD DO, GRANDMA SHARK DO DOD DOD DO, GRANDPA SHARK DO DOD DOD DO, LETS GO HUNT DO DOD DOD DO, RUN AWAY DO DOD DOD DO, SAFE AT LAST DO DOD DOD DO, ITS THE END DO DOD DOD DO,',
};
